// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2XtUpvevrrzwbxD8IVj80SdsYH0uOAo',
    appId: '1:675215871075:web:52c3ca4c489ed2b0dabc56',
    messagingSenderId: '675215871075',
    projectId: 'my-asiec',
    authDomain: 'my-asiec.firebaseapp.com',
    storageBucket: 'my-asiec.firebasestorage.app',
    measurementId: 'G-08BXS7S5F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4oCSfWGFNpvTzyqu9lrg0J6MzZo0qHA',
    appId: '1:675215871075:android:9f21ad229e2b7309dabc56',
    messagingSenderId: '675215871075',
    projectId: 'my-asiec',
    storageBucket: 'my-asiec.firebasestorage.app',
  );
}
